export const GET_PRODUCTS = "GET_PRODUCTS";
export const NEW_PRODUCT = "NEW_PRODUCT";
export const DETAIL_PRODUCT = "DETAIL_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
